apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy-client
  name: proxy-client
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-client
  template:
    metadata:
      labels:
        io.kompose.service: proxy-client
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: acr-secret
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: proxy-client
          envFrom:
            - configMapRef:
                name: common-environment-variables
          name: proxy-client
          image: microservicesacr5fa48984.azurecr.io/proxy-client:stage
          imagePullPolicy: Always
          ports:
            - containerPort: 8900
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "768Mi"
            limits:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: proxy-client
  name: proxy-client
  namespace: dev
spec:
  ports:
    - name: "8900"
      port: 8900
      targetPort: 8900
  selector:
    io.kompose.service: proxy-client
